### ISSUE TITLE
Suggestions for Console Support

### ISSUE THREAD

**Issue by AidenTREplayz09** [Tria-Studio/Tria-Issues#159]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a map with a sliding section and/or a swimming section appears, and as a console player, I cannot play those maps.

**Describe the solution you'd like**
I would like some way to reach the Controls section of the settings menu, so I can set slide and swim buttons for console adaptation. For example, you could add Roblox's virtual cursor system into the game, so console players can reach controls, or set a default keybind setting depending on the system the player is using.

**Additional context**
No additional context.

**Comment by HatKip** [comment]
This would be great, it's impossible to change your keybinds because the GUI selection system just doesn't work properly in this game. Games such as FNB use Roblox virtual cursor system and don't have this issue.

It would be also nice to remove the camera easing and change it the way it works in FE2 so it's easier to handle with a joystick, because right now it's almost unplayable.

Sadly, its been months and it seems like they don't care about console support at all.

**Comment by grif-0** [comment]
Controller support has improved for 0.11.

Menu navigation has improved greatly without the need for the virtual cursor (i personally feel like this is taking the easy way out of proper ui navigation, but i also dont play with a controller a lot). Its now possible to change your keybinds when on controller. Im gonna experiment with automatic keybind changing for keyboard / controller soon before the release of 0.11 aswell.

Were aware of some issues with the camera with controllers and have tried fixing it with no luck, but gonna continue to investigate
